spring:
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

storage:
  types: [] # Empty by default, will be set via request
  serverUrl: ${SERVER_URL:http://localhost:8080}
  localTempPath: ${STORAGE_LOCAL_TEMP_PATH:/tmp/streams}
  # AWS Configuration (optional)
  awsAccessKey: ${AWS_ACCESS_KEY:}
  awsSecretKey: ${AWS_SECRET_KEY:}
  awsBucket: ${AWS_BUCKET:}
  # Azure Configuration (optional)
  azureConnectionString: ${AZURE_CONNECTION_STRING:}
  azureContainer: ${AZURE_CONTAINER:}
  # GCP Configuration (optional)
  gcpProjectId: ${GCP_PROJECT_ID:}
  gcpBucket: ${GCP_BUCKET:}

server:
  port: 8080
